#ifndef COMMON_DEFINES_H
#define COMMON_DEFINES_H

#define MAX_UNDO_SLOTS 10
#define MAX_FILE_NAME 100
#define TEXT_BUFFER_SIZE 2000
#define INPUT_BUFFER_SIZE 200
#define STACK_SIZE 2000
#define NO_BASENAME
#define PATH_MAX 200
#define NO_BLORB

#endif
